Repository DHBW-Malte/gardeningApp, pull requests merged in 2024-11, with the labels that each got.

#57 Design implementation login logout
  .gitignore
  docs/_posts/2024-10-17-our-first-narratives.md
  docs/_posts/2024-10-23-project-management.md
  docs/_posts/2024-10-24-retrospective.md
  docs/assets/css/style.css
  docs/assets/screenshots/retro.png
  docs/assets/screenshots/screenshot_gherkin.png
  docs/assets/svg/GreenFingersUsecases.drawio.svg
  docs/assets/svg/Use Case Diagrams/addPlant.drawio.svg
  docs/assets/svg/Use Case Diagrams/viewPlant.drawio.svg
  docs/assets/svg/useCaseDiagrams/addPlant.drawio.svg
  docs/assets/svg/useCaseDiagrams/viewPlant.drawio.svg
  docs/assets/svg/useCaseWireframes/addPlant.png
  docs/usecases/addPlant.md
  docs/usecases/databaseStructure.lua
  docs/usecases/viewPlant.md
  green-fingers/.gitignore
  green-fingers/app.json
  green-fingers/app/(auth)/forgotpassword.tsx
  green-fingers/app/(auth)/login.tsx
  green-fingers/app/(auth)/signup.tsx
  green-fingers/app/_layout.tsx
  green-fingers/app/index.tsx
  green-fingers/app/profile/_layout.tsx
  green-fingers/app/profile/gardens.tsx
  green-fingers/assets/fonts/Montserrat-Italic.ttf
  green-fingers/assets/fonts/Montserrat-Medium.ttf
  green-fingers/assets/fonts/Montserrat-MediumItalic.ttf
  green-fingers/assets/fonts/Montserrat-Regular.ttf
  green-fingers/babel.config.js
  green-fingers/components/Button.tsx
  green-fingers/components/Input.tsx
  green-fingers/constants/colors.ts
  green-fingers/constants/textStyles.ts
  green-fingers/cucumber.js
  green-fingers/features/step_definitions/stepdefs.js
  green-fingers/features/viewPlant.feature
  green-fingers/firebase/firebaseConfig.ts
  green-fingers/package-lock.json
  green-fingers/package.json
  green-fingers/tsconfig.json
Labels: Implementation

#67 Add profil view and update user info function
  green-fingers/app/(profilePage)/_layout.tsx
  green-fingers/app/(profilePage)/profilePage.tsx
  green-fingers/app/profile/_layout.tsx
  green-fingers/components/Button.tsx
  green-fingers/components/Input.tsx
  green-fingers/constants/textStyles.ts
  green-fingers/context/AuthContext.tsx
  green-fingers/hooks/useForm.ts
  green-fingers/package-lock.json
  green-fingers/types/authtypes.ts
Labels: UC: Manage Users

#83 Added user profile link to db
  green-fingers/app/(profilePage)/profilePage.tsx
  green-fingers/context/AuthContext.tsx
  green-fingers/context/GardensAndPlantsContext.tsx
  green-fingers/firebase/addPlants.ts
  green-fingers/firebase/plantService.ts
  green-fingers/hooks/useForm.ts
  green-fingers/hooks/usePlants.ts
  green-fingers/package-lock.json
Labels: Environment
